/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/attendances/': RouteRecordInfo<'/attendances/', '/attendances', Record<never, never>, Record<never, never>>,
    '/auth/create-password': RouteRecordInfo<'/auth/create-password', '/auth/create-password', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/oldlogin': RouteRecordInfo<'/auth/oldlogin', '/auth/oldlogin', Record<never, never>, Record<never, never>>,
    '/auth/otp': RouteRecordInfo<'/auth/otp', '/auth/otp', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/verify-account': RouteRecordInfo<'/auth/verify-account', '/auth/verify-account', Record<never, never>, Record<never, never>>,
    '/events/': RouteRecordInfo<'/events/', '/events', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/sites/': RouteRecordInfo<'/sites/', '/sites', Record<never, never>, Record<never, never>>,
    '/users/users': RouteRecordInfo<'/users/users', '/users/users', Record<never, never>, Record<never, never>>,
  }
}
