name: CI

on:
  push:
    branches: [main, front, develop]
  pull_request:
    branches: [main, front]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./front/package-lock.json

      - run: npm ci
      - run: npm run lint:ci
      - run: npm test
      - run: npm run build
